---
- name: debug
  debug: msg="Load Balancer @ {{ inventory_hostname }}"
  tags:
   - debug
   - loadbalancer
- name: install nginx
  yum: pkg={{item}} state=latest
  with_items:
   - nginx
   - nginx-mod-stream
  become: yes
  become_user: root
  tags:
   - setup
   - loadbalancer
- name: configure nginx
  template: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644
  become: yes
  become_user: root
  tags:
   - setup
   - loadbalancer
- name: enable and start nginx
  service: name=nginx enabled=yes state=started
  become: yes
  become_user: root
  tags:
   - setup
   - loadbalancer
