
---
- name: install postgres
  yum: pkg={{item}} state=latest
  with_items:
   - postgresql95-server
   - postgresql95-contrib
  become: yes
  become_user: root
  tags:
   - setup
   - postgres
- stat: path=/var/lib/pgsql95/data/pg_xlog
  become: yes
  become_user: root
  register: pgdata_xlog
  tags:
   - setup
   - postgres
- command: "service postgresql95 initdb"
  become: yes
  become_user: root
  when: pgdata_xlog.stat.exists == False
  tags:
   - setup
   - postgres
- name: configure postgres (pg_hba.conf)
  template: src=pg_hba.conf dest=/var/lib/pgsql95/data/pg_hba.conf owner=postgres group=postgres mode=0600
  become: yes
  become_user: root
  tags:
   - setup
   - postgres
- name: configure postgres (postgresql.conf)
  template: src=postgresql.conf dest=/var/lib/pgsql95/data/postgresql.conf owner=postgres group=postgres mode=0600
  become: yes
  become_user: root
  tags:
   - setup
   - postgres
- name: enable and start postgres
  service: name=postgresql95 enabled=yes state=started
  become: yes
  become_user: root
  tags:
   - setup
   - postgres
